# This is a basic workflow to help you get started with Actions

name: Deploy to Apigee X Prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Auth with Google
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          project_id: ${{ secrets.APIGEE_ORG }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Running mvn command
        run:  mvn -f pom.xml -ntp process-resources apigee-enterprise:configure -Pprod -Dorg=${{ secrets.APIGEE_ORG }} -Denv=${{ secrets.APIGEE_ENV }}
      - name: Deploy Bundle 
        id: deploy
        run: mvn -f pom.xml -ntp apigee-enterprise:deploy -Pprod -Dorg=${{ secrets.APIGEE_ORG }} -Denv=${{ secrets.APIGEE_ENV }} -Dbearer=${{steps.auth.outputs.access_token}}

